sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database:
    username: root
    password:
  alioss:
    endpoint:
    bucket-name:
    access-key-id:
    access-key-secret:
  redis:
    host: localhost
    port: 6379
    password:
    database: 6
  wechat:
    appid:
    secret:
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:
  shop:
    address:
  baidu:
    ak: